
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/AKSoftware.Localization.MultiLanguages.csproj'
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: $(solution)
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'

- task: NDependTask@1
  inputs:
    viewname: 'First Perspective'

- task: DotNetCoreCLI@2
  displayName: 'Packing the library'
  inputs:
    command: 'pack'
    packagesToPack: '$(solution)'
    nobuild: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'


